# Artificial Neural Network

Regression for a combined cycle power plant.
Goal. Predict the Energy Output of the power plant. 



### Importing the libraries

In [16]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [17]:
tf.__version__

'2.3.0'

## Part 1 - Data Preprocessing

### Importing the dataset
The features contained in the dataset consist of hourly average ambient variables

#Independent Variables contained in matrix X
- Temperature (T) in the range 1.81°C and 37.11°C,
- Ambient Pressure (AP) in the range 992.89-1033.30 milibar,
- Relative Humidity (RH) in the range 25.56% to 100.16%
- Exhaust Vacuum (V) in teh range 25.36-81.56 cm Hg

#Output to Predict (y_pred)
- Net hourly electrical energy output (EP) 420.26-495.76 MW
The averages are taken from various sensors located around the plant that record the ambient variables every second. The variables are given without normalization.



In [18]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [19]:
print(X)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

Train set to train the neural network and test one to compare the results

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Part 2 - Building the ANN

Build an ANN with two hidden layers
Input layer and of course Output layer

In [21]:
# use tensorflow to build the neural network
# build a sequencial ANN
ann = tf.keras.models.Sequential()

# add the input layer and first hidden layer to the ANN
# add the dense class tf.keras.layers.Dense
# Dense means that the entire input layer is fully connected to all the neurons in the hidden layer
# units = number of hidden neurons 
# relu. rectifier activation function
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

# adding a second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))


### Adding the output layer

In [22]:
# remove the activation function to none because the ANN is used for regression
# for classification of two parameters would be ok a sigmoid, with more parameters max function
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

In [23]:
#compile method optimizer parameter = adam (for stochastic gradient descent)
# loss is the cost function
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

In [24]:
# use fit method to train the ANN
# inputs in addtion to the train set, batch size and epochs
# # of epochs select a random number and then nmodify if needed 
# batch size , amount of data to be propagated in each round
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 [==============================] - 0s 913us/step - loss: 2317.2610
Epoch 2/100
240/240 [==============================] - 0s 835us/step - loss: 145.5974
Epoch 3/100
240/240 [==============================] - 0s 837us/step - loss: 136.1490
Epoch 4/100
240/240 [==============================] - 0s 867us/step - loss: 125.7509
Epoch 5/100
240/240 [==============================] - 0s 900us/step - loss: 114.5272
Epoch 6/100
240/240 [==============================] - 0s 868us/step - loss: 103.4453
Epoch 7/100
240/240 [==============================] - 0s 850us/step - loss: 93.6749
Epoch 8/100
240/240 [==============================] - 0s 813us/step - loss: 83.7130
Epoch 9/100
240/240 [==============================] - 0s 881us/step - loss: 75.6617
Epoch 10/100
240/240 [==============================] - 0s 912us/step - loss: 68.6488
Epoch 11/100
240/240 [==============================] - 0s 875us/step - loss: 62.9203
Epoch 12/100
240/240 [==============================] - 

it began to converge after 53 epochs or so

### Predicting the results of the Test set

after the minimization process it is possible to see that the results are quite similar

In [25]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[431.51 431.23]
 [462.78 460.01]
 [466.35 461.14]
 ...
 [473.53 473.26]
 [440.34 438.  ]
 [459.58 463.28]]
